### ISSUE TITLE
Good item bases + influence are not detected with ctrl+d

### ISSUE THREAD

**Issue by dclamage** [r52/PTA#13]
See image here: https://i.imgur.com/ejGvb92.png

With advanced search and ONLY taking into account item base + influence + ilvl, you can see it's worth probably 4c (maybe even 10c). However, with ctrl+d it says 1.3 - 2 chaos.

Is there any way to make sure a quick ctrl+d won't misjudge good item bases? There are items worth multiple exalts just from their ilvl + base + influence alone. See this search for an example: https://www.pathofexile.com/trade/search/Metamorph/pJR5bRvH0

**Comment by r52** [comment]
No.

As you can see by the disclaimer at the bottom of the prediction dialog, Ctrl+D predictions are sourced from poeprices.info, and they use machine learning to try and predict the prices of items based on mods etc, but it's clear that their algorithm and model doesn't work well with influenced item bases at specific ilvl checkpoints.

This is wholly outside of my control and there's nothing I can or would do to "fix" it, as this was originally a "feature" that was straight up copied from PoE-TradeMacro to feature-match the tools. 

The best I can do here is to add an option that lets you disable poeprices.info prediction altogether so that you don't see them at all.

**Comment by r52** [comment]
751293d8e8ed5ac00c005bc7d6a277bada300620 adds an option to disable poeprices.info
