### ISSUE TITLE
missed vcruntime140_1.dll

### ISSUE THREAD

**Issue by UlrichVonRekkenin** [r52/PTA#29]
IMHO `windeployqt` couldn`t find *all* needed files.

**Comment by r52** [comment]
From the README:
> **If your PC is not running Windows 10 with the latest feature updates or you are getting a VC runtime error, you MUST download and install the [Microsoft Visual C++ Redistributable](https://aka.ms/vs/16/release/VC_redist.x64.exe)!**

I intentionally don't package the VC runtimes with PTA because I don't create an installer, and its better for your system to have a non-local installation of VC runtimes anyways. Besides that, having vcruntime.dll in the folder is not enough for PTA to run. There are several components besides vcruntime.dll that it depends on from the VC runtimes package.
