### ISSUE TITLE
DPI scaling and high contrast

### ISSUE THREAD

**Issue by djinnsynth** [r52/PTA#34]
Sorry about all these simple issues btw!

I have a 1440p monitor and a high contrast theme for windows and PTA seems to be confused about what to do, screen shot will explain . . .

![image](https://user-images.githubusercontent.com/60988604/76822623-62611c00-685d-11ea-9d14-202376342c3f.png)

The theme is great buuuuut, there's a dirty scrollbar and the edge of the window is black. I'm sure it's just my DPI and windows theme but I was wondering if you could include some exception in your code to force a size and scrollbar?

This was the reason I was digging about in the code but tbh I don't know enough to change this.

Cheers!

**Comment by r52** [comment]
In order to create a custom frameless window theme in Qt, you have to first set the flag to hide the native window then proceed to manually create and style custom components that replicate the original OS functions, like the title bar and the 3 system menu buttons. However, Qt, seems to leaves a margin between the native frame and custom components that you'd hide by setting the dialog background translucent. But it seems that this doesn't work on the high contrast theme. I will see if I can eliminate the margin entirely, but it's the little things like these that makes me want to consider dropping this codebase entirely and porting PTA to something more UI oriented like Electron.

The scrollbar should be styleable with CSS.

**Comment by r52** [comment]
Try [this build](https://github.com/r52/PTA/actions/runs/57613713) and see if it hides your issues.

**Comment by djinnsynth** [comment]
![image](https://user-images.githubusercontent.com/60988604/76883939-9b82a600-68c8-11ea-944a-0fe3ce9f1db4.png)

Can see the scrollbar is different yes, although the black frame is still there. It'd be nicer if everything was smaller, I think windows DPI at 200% (which is actually comfy for me) is making it huge?

I'll send a screen of no high contrast too

**Comment by djinnsynth** [comment]
Yep that black is definitely the win theme:

![image](https://user-images.githubusercontent.com/60988604/76884215-0f24b300-68c9-11ea-948d-ecde35ab12d7.png)

**Comment by r52** [comment]
Give [this build](https://github.com/r52/PTA/actions/runs/57671705) a try.  If this doesn't work, then the issue is probably beyond what I can do with the library.

**Comment by djinnsynth** [comment]
Oh you did it!

![image](https://user-images.githubusercontent.com/60988604/76902264-5a4dbe80-68e7-11ea-87e3-d50425cbf3ea.png)

Only thing that hasn't scaled/is still blurry is the close/min/max buttons now.

Thanks for making those edits!
